ExpenceInvoice/objects/Expense__c.object
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExpenceInvoice/objects/Expense_Member__c.object
<CustomObject>
    <fields>
        <fullName>Contribution_Amount__c</fullName>
        <label>Contribution Amount</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense Members</relationshipLabel>
        <relationshipName>Expense_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expense Members</relationshipLabel>
        <relationshipName>Expense_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense Member</label>
    <nameField>
        <displayFormat>ExpenseMember-{000000}</displayFormat>
        <label>Expense_Member_Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExpenceInvoice/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExpenceInvoice/classes/ExpenseEXT.cls
public with sharing class ExpenseEXT {
    public Expense__c expObj{get;set;}                                 //reference variable of Expense object
    public List<Expense_Member__c> memExp{get;set;}                    //List of Expense Member object
    public ExpenseEXT(ApexPages.StandardController controller) {       
        expObj = (Expense__c)controller.getRecord();
        memExp = getExpMembers();
     }
    
    public List<Expense_Member__c> getExpMembers(){
       return [Select Member__r.Name,Contribution_Amount__c from Expense_Member__c where Expense__c =: expObj.Id];   //return list of Expense Member object
    }
}