ExpenceInvoice/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExpenceInvoice/objects/Expense_Member__c.object
<CustomObject>
    <fields>
        <fullName>Contribution_Amount__c</fullName>
        <label>Contribution Amount</label>
        <precision>10</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense Members</relationshipLabel>
        <relationshipName>Expense_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expense Members</relationshipLabel>
        <relationshipName>Expense_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense Member</label>
    <nameField>
        <displayFormat>ExpenseMember-{000000}</displayFormat>
        <label>Expense_Member_Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExpenceInvoice/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExpenceInvoice/classes/ExpenseTest.cls
@isTest

public class ExpenseTest {                                                   // Test class
    public testMethod static void myTest() {                                // Test method
        Expense__c expense = new Expense__c();                             // Expense Test object
            expense.Amount__c=1000;                                       // Test value for Amount field
            expense.Name='party';                                         // Test value for Name field
            expense.Event_Date__c = system.today();                       //  Test value for Event Date field
            insert expense;                                               // Inserting expence object field value for test run
                                                          
        Member__c member = new Member__c();                               // Expense Member object
            member.Name='abc';                                           // Test value for Name field
            member.Email__c='abc@abc.com';                               // Test value for Email field          
            insert member;                                               // Inserting Member object field value for test run
                                                           
        Expense_Member__c expmem = new Expense_Member__c();              // Expense Member object
            expmem.Member__c=member.Id;                                  // Test value for Member lookup field
            expmem.Expense__c=expense.Id;                                // Test value for Expense lookup field                              
            expmem.Contribution_Amount__c=100;                           // Test value for Contribution Amount field
            insert expmem;                                               // Inserting Expense Member object field value for test run
             
        ExpenseEXT expExt = new ExpenseEXT(new ApexPages.StandardController(expense));        // ExpenseEXT object
            expExt.getExpMembers();                                                           
                                                                       
        
            
        
    }
}